# Gradle settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft / Forge versions
minecraft_version=1.21
minecraft_version_range=[1.21,1.22)
forge_version=51.0.33
forge_version_range=[51,)
loader_version_range=[51,)

# Dependencies
jei_version=19.8.2.99

# Mappings
mapping_channel=official
mapping_version=1.21

# Mod identification
mod_id=immersiveores
mod_name=ImmersiveOres
mod_group_id=com.blocklegend001

# Mod metadata
mod_version=1.21-1.1.5
mod_license=All Rights Reserved
mod_authors=Block_Legend001
mod_description=Immersive Ores adds three new ores to the game: Vibranium, Vulpus, and Enderium. It improves cave and mining experience and introduces new armor and tools with special abilities.
