# Gradle
org.gradle.jvmargs=-Xmx4G

# Minecraft / Loader
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.3
loom_version=1.14-SNAPSHOT
fabric_version=0.140.0+1.21.11

# Mod identification / metadata
mod_version=1.21.11-0.2
maven_group=com.blocklegend001
archives_base_name=ImmersiveOres

# Dependencies
wthitVersion=18.0.4
badpacketsVersion=0.11.2
pal_version=1.15.0