# Gradle
org.gradle.jvmargs=-Xmx4G

# Minecraft / Loader
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
loader_version=0.16.14
fabric_version=0.121.0+1.21.5

# Mod identification / metadata
mod_version=1.21.5-1.1.3
maven_group=com.blocklegend001
archives_base_name=ImmersiveOres

# Dependencies
rei_version=19.0.806
wthitVersion=15.0.2
badpacketsVersion=0.8.2
pal_version=1.13.0
modmenu_version=14.0.2